"""
Math Flashcards
------------------------------
Code generated by AI with human assistance. This is a proof of concept that
educators can use AI to build software tailored to the needs of their own
schools. Almost all code was written by Anthropic's Claude 3.5 Sonnet.

License: MIT License (applies to original code only)
Copyright (c) 2024 JD Jones

This project uses third-party open source software under separate licenses:
- Pygame (LGPL v2.1)
- PyInstaller (GPL with linking exception)
- Setuptools (MIT)

See README.md for full attribution and license details.
"""

from setuptools import setup, find_packages
import os
import sys
from math_flashcards.utils.version import (
    VERSION, APP_NAME, APP_AUTHOR, APP_COPYRIGHT,
    APP_LICENSE, APP_REPOSITORY, WINDOWS_METADATA
)

# Additional build requirements for executables
build_requires = [
    'pygame',
    'pyinstaller',
]

if sys.platform.startswith('win'):
    # Windows-specific requirements
    build_requires.extend([
        'pywin32',  # For Windows-specific features
    ])

setup(
    name="math_flashcards",
    version="v0.8.7",
    author="JD Jones",
    description="Open Source Interactive Math Practice Application",
    long_description=open(
        os.path.join(os.path.dirname(__file__), 'README.md'),
        encoding='utf-8'
    ).read(),
    long_description_content_type="text/markdown",
    url=APP_REPOSITORY,
    packages=find_packages(),
    install_requires=[
        'pygame>=2.0.0',
    ],
    extras_require={
        'build': build_requires,
    },
    python_requires='>=3.8',
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Education',
        'Topic :: Education :: Computer Aided Instruction (CAI)',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Operating System :: OS Independent',
        'Environment :: X11 Applications',
        'Environment :: Win32 (MS Windows)',
        'Environment :: MacOS X',
    ],
    project_urls={
        'Source': APP_REPOSITORY,
        'Tracker': f"{APP_REPOSITORY}/issues",
        'Documentation': f"{APP_REPOSITORY}/wiki",
    },
    include_package_data=True,
    zip_safe=False,
    license=APP_LICENSE,
)